### ISSUE TITLE
Example of Snowpack setup

### ISSUE THREAD

**Issue by hengnee** [mxmul/snowpack-plugin-markdown-html#1]
Hi, this isn't really an issue but I think it'll be super great if an example for how to use this package would really help in using it.
Really love the work bbut have no idea how to incoporate into my Svelte project and have been trying for days...

Thank you so much in advance!

**Comment by mxmul** [comment]
hi @hengnee! sorry, you found this repo before it was totally ready for public consumption :)

I've added some example projects in the repo, which I hope will help: https://github.com/mxmul/snowpack-plugin-markdown-html/tree/master/examples
